#!/usr/bin/env bash

# To implement this command, edit the "Command implementation" section below. 

# Usage
# -----

# Comments prefixed with `#/` are managed by stubbs.
# The `command` and `usage` comments describe the command
# and show its options.
# 
#/ command: sf2:load-fixtures: "load all fixtures"
#/ usage: rerun sf2:load-fixtures [options]

# Load common functions
# ---------------------

# Load the function library for this module.
# This loads rerun functions, too.
. $RERUN_MODULE_DIR/lib/functions.sh load-fixtures || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------

# This script is designed to _fail-fast_.

# Trap errors and exit. The call to `rerun_die` will print the
# the error message and exit with the error command exit status. 

trap 'rerun_die $? "*** command failed: sf2:load-fixtures. ***"' ERR

# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
# so a pipeline return status is the value of the last 
# (rightmost) command to exit with non-zero status.
#
# [set]: http://ss64.com/bash/set.html
# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html

set -o nounset -o pipefail

# Command variables
# -----------------

# This command script can access the following variables
# declared by `rerun` or by the option parser function.

#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: 

# The `rerun_options_parse` function processes the command line
# arguments. Each accepted command line flag results in setting 
# one the corresponding option variables.

rerun_options_parse "$@"


# Command implementation
# ----------------------
php app/console --env=dev doctrine:database:drop --connection=default --force
php app/console --env=dev doctrine:database:create --connection=default
php app/console --env=dev doctrine:database:drop --connection=other1 --force
php app/console --env=dev doctrine:database:create --connection=other1

php app/console --env=dev doctrine:schema:update --force --em=default
php app/console --env=dev doctrine:schema:update --force --em=other1
#php app/console --env=dev doctrine:schema:update --force --em=slave
#php app/console --env=dev doctrine:schema:update --force --em=other2
php app/console --env=dev doctrine:fixtures:load --no-interaction --em=default
php app/console --env=dev doctrine:fixtures:load --no-interaction --em=other1

# - - -
# Put the command implementation here.
# - - -

# Done. Exit with last command exit status.
exit $?

